token: x***-********-********-****************
name: bot
icon: https://****.**/***/***.png
order:
  text: DEFAULT
group:
  text: DEFAULT
gcalendar:
  gas: https://script.google.com/macros/s/******/exec
  channel: calendar
  time: mon9
  colors: [f8e352, d5848b, 7b9ad0, 51a1a2, ae8dbc, c08e47, e5ab47]
  msg: お疲れ様です！今週も頑張っていきましょう！
